[project]
name = 'Tokenized-Specialized-Film-Music-Rights'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.composition-registration]
path = 'contracts/composition-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.royalty-distribution]
path = 'contracts/royalty-distribution.clar'
clarity_version = 2
epoch = 2.5

[contracts.usage-licensing]
path = 'contracts/usage-licensing.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
